# Use postgres/example user/password credentials
version: '3.1'

services:
  #postgres-my-first-convig-v1
  # db:
  #   image: postgres
  #   restart:  unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: zaq1@WSX
  #     POSTGRES_USER: admin
  #   volumes:
  #     - ${POSTGRES_DATA_PATH}:/var/lib/postgresql
  #adminer
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  #postgres-stolen-config
  postgres:
    container_name: postgres_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4      
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data:rw
