version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: lupa_rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=lupa_maint"
      - "RABBITMQ_DEFAULT_PASS=Qaz12345"
      - "RABBITMQ_DEFAULT_VHOST=lupa_maint"
    restart: unless-stopped
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   user: root
  #   container_name: lupa_mssql
  #   # network_mode: "host"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: Qaz12345
  #     MSSQL_PID: Developer
  #     # MSSQL_AGENT_ENABLED: 1
  #   restart: unless-stopped
  #   volumes:
  #     - ${MSSQL_DATA_PATH}:/var/opt/mssql/data
  #     - ${MSSQL_LOGS_PATH}:/var/opt/mssql/logs
  #   ports:
  #     - 1433:1433
  #     - 1434:1434/udp
  # postgres:
  #   image:
  #   container_name: lupa_postgres
  #   environment:
  #   restart: unless-stopped
  #   # volumes:
  #     # - ${POSTGRES_DATE_PATH}:/postgres
  seq:
    image: datalust/seq
    container_name: lupa_seq
    environment:
      - "ACCEPT_EULA=Y"
      # - "SEQ_FIRSTRUN_ADMINUSERNAME=biggy"
      # - "SEQ_FIRSTRUN_ADMINPASSWORD=Qaz12345"
    restart: unless-stopped
    volumes:
      - ${SEQ_DATA_PATH}:/data
    ports:
      - 8765:80
      - 5341:5341
