version: '3.7'

services:
  app:
    image: nextcloud:latest
    hostname: rog
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./mount/nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=*
      #- POSTGRES_DB_FILE=/run/secrets/postgres_db
      #- POSTGRES_DB_FILE=/run/secrets/postgres_db
      #- POSTGRES_USER_FILE=/run/secrets/postgres_user
      #- POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      #- NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      #- NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      # - POSTGRES_HOST=localhost
      # - POSTGRES_DB_FILE=/run/secrets/postgres_db
      # - POSTGRES_USER_FILE=/run/secrets/postgres_user
      # - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      # - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      # - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username in this file
